version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:474007463914:task-definition/authentication-task:1"
        LoadBalancerInfo:
          ContainerName: "authentication"
          ContainerPort: "8089"
        PlatformVersion: "LATEST"